/**
 * MineralOps Pipeline — Manufacturing E2E data model
 * Modules (ERP / CRM / process tracks), category-specific phases, KPIs
 */
window.MineralOpsData = (function () {
  "use strict";

  /**
   * Each module mirrors a manufacturing business domain
   * (ERP-style process + commercial / finance extensions).
   * phases[] = stage gates for THAT module only
   * kpis[]   = key metrics operators & developers track
   */
  const MODULES = [
    {
      id: "production",
      name: "Production & Process",
      short: "Production",
      erp: "MES / Production Order",
      icon: "⚙",
      color: "#c4783a",
      description:
        "Plant execution: throughput, recovery, OEE, batch/campaign control from plan to ship.",
      processTrack: "Make-to-order / make-to-stock process tracking",
      phases: [
        { id: "plan", label: "Production Plan" },
        { id: "schedule", label: "Schedule & Crew" },
        { id: "release", label: "Order Release" },
        { id: "execute", label: "Line Execution" },
        { id: "qc_hold", label: "In-Process QC" },
        { id: "complete", label: "Order Complete" },
        { id: "ship_ready", label: "Ship-Ready / FG" },
        { id: "closed", label: "Closed / Costed" },
      ],
      kpis: [
        { id: "oee", name: "OEE", unit: "%", better: "higher", target: 85 },
        { id: "recovery", name: "Metal Recovery", unit: "%", better: "higher", target: 92 },
        { id: "throughput", name: "Throughput", unit: "t/day", better: "higher", target: 1200 },
        { id: "downtime", name: "Unplanned Downtime", unit: "h/wk", better: "lower", target: 8 },
        { id: "first_pass", name: "First-Pass Yield", unit: "%", better: "higher", target: 96 },
      ],
    },
    {
      id: "process_efficiency",
      name: "Process Efficiency",
      short: "Process Eff.",
      erp: "Process / Continuous Improvement",
      icon: "↑",
      color: "#d4894a",
      description: "Unit-operation optimization: leach, flotation, furnace, reagent intensity.",
      processTrack: "DMAIC / stage-gate improvement",
      phases: [
        { id: "submitted", label: "Idea Submitted" },
        { id: "baseline", label: "Baseline KPI" },
        { id: "root_cause", label: "Root Cause" },
        { id: "design", label: "Solution Design" },
        { id: "pilot", label: "Pilot Trial" },
        { id: "validate", label: "Result Validation" },
        { id: "standardize", label: "SOP / Standardize" },
        { id: "realized", label: "Realized" },
      ],
      kpis: [
        { id: "recovery_delta", name: "Δ Recovery", unit: "pp", better: "higher", target: 1.5 },
        { id: "reagent_use", name: "Reagent Intensity", unit: "kg/t", better: "lower", target: 12 },
        { id: "energy_t", name: "Energy / tonne", unit: "kWh/t", better: "lower", target: 450 },
        { id: "cycle_time", name: "Batch Cycle Time", unit: "h", better: "lower", target: 18 },
      ],
    },
    {
      id: "supply_chain",
      name: "Supply Chain & Logistics",
      short: "Supply Chain",
      erp: "SCM / Logistics",
      icon: "⬡",
      color: "#d4a017",
      description: "Inbound feedstock, freight, inventory policy, outbound product logistics.",
      processTrack: "Plan → Source → Deliver",
      phases: [
        { id: "demand", label: "Demand Signal" },
        { id: "source", label: "Source / RFQ" },
        { id: "contract", label: "Contract" },
        { id: "inbound", label: "Inbound Transit" },
        { id: "receive", label: "Receive & QC" },
        { id: "inventory", label: "Inventory Position" },
        { id: "outbound", label: "Outbound / Deliver" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "otif", name: "OTIF", unit: "%", better: "higher", target: 95 },
        { id: "lead_time", name: "Supplier Lead Time", unit: "days", better: "lower", target: 21 },
        { id: "stockout", name: "Stockout Events", unit: "/mo", better: "lower", target: 0 },
        { id: "freight_cost", name: "Freight Cost / t", unit: "$/t", better: "lower", target: 45 },
        { id: "inventory_days", name: "Inventory Days", unit: "days", better: "lower", target: 28 },
      ],
    },
    {
      id: "procurement",
      name: "Procurement",
      short: "Procurement",
      erp: "Procure-to-Pay (P2P)",
      icon: "▣",
      color: "#b8956c",
      description: "Requisitions, PO, vendor qualification, invoice match for reagents & MRO.",
      processTrack: "Requisition → PO → GRN → Invoice",
      phases: [
        { id: "req", label: "Requisition" },
        { id: "approve", label: "Budget Approve" },
        { id: "rfq", label: "RFQ / Bid" },
        { id: "po", label: "PO Issued" },
        { id: "asn", label: "ASN / In Transit" },
        { id: "grn", label: "Goods Receipt" },
        { id: "invoice", label: "3-Way Match" },
        { id: "paid", label: "Paid / Closed" },
      ],
      kpis: [
        { id: "savings", name: "Purchase Savings", unit: "%", better: "higher", target: 5 },
        { id: "maverick", name: "Maverick Spend", unit: "%", better: "lower", target: 3 },
        { id: "cycle_po", name: "PR→PO Cycle", unit: "days", better: "lower", target: 5 },
        { id: "vendor_otd", name: "Vendor OTD", unit: "%", better: "higher", target: 92 },
      ],
    },
    {
      id: "inventory",
      name: "Inventory & Warehouse",
      short: "Inventory",
      erp: "WMS / Inventory",
      icon: "▤",
      color: "#8a9a6a",
      description: "RM, WIP, FG, consumables; lot/batch traceability and cycle counts.",
      processTrack: "Receive → Putaway → Pick → Issue",
      phases: [
        { id: "receive", label: "Receive" },
        { id: "putaway", label: "Putaway" },
        { id: "available", label: "Available" },
        { id: "reserved", label: "Reserved" },
        { id: "pick", label: "Pick / Issue" },
        { id: "adjust", label: "Count / Adjust" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "accuracy", name: "Inventory Accuracy", unit: "%", better: "higher", target: 99 },
        { id: "turns", name: "Inventory Turns", unit: "x/yr", better: "higher", target: 8 },
        { id: "wip_days", name: "WIP Days", unit: "days", better: "lower", target: 5 },
        { id: "obsolete", name: "Obsolete Stock $", unit: "k$", better: "lower", target: 50 },
      ],
    },
    {
      id: "quality",
      name: "Quality & Yield",
      short: "Quality",
      erp: "QMS / LIMS",
      icon: "◇",
      color: "#5a9fc4",
      description: "Assay, CoA, nonconformance, CAPA, customer spec compliance.",
      processTrack: "Sample → Assay → Disposition → CAPA",
      phases: [
        { id: "sample", label: "Sample Taken" },
        { id: "assay", label: "Assay / Test" },
        { id: "review", label: "Result Review" },
        { id: "disposition", label: "Disposition" },
        { id: "ncr", label: "NCR (if fail)" },
        { id: "capa", label: "CAPA" },
        { id: "release", label: "Lot Release" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "fpy", name: "First-Pass Yield", unit: "%", better: "higher", target: 97 },
        { id: "defect_ppm", name: "Defect Rate", unit: "ppm", better: "lower", target: 500 },
        { id: "coa_ontime", name: "CoA On-Time", unit: "%", better: "higher", target: 99 },
        { id: "ncr_close", name: "NCR Close Days", unit: "days", better: "lower", target: 14 },
      ],
    },
    {
      id: "maintenance",
      name: "Maintenance & Reliability",
      short: "Maintenance",
      erp: "CMMS / EAM",
      icon: "⚒",
      color: "#7a8a9a",
      description: "PM, breakdowns, spares, reliability for crushers, mills, pumps, furnaces.",
      processTrack: "Notify → Plan → Execute → Close WO",
      phases: [
        { id: "notify", label: "Notification" },
        { id: "plan", label: "Plan / Parts" },
        { id: "schedule", label: "Schedule" },
        { id: "execute", label: "Execute WO" },
        { id: "test", label: "Test Run" },
        { id: "close", label: "Close & History" },
      ],
      kpis: [
        { id: "mtbf", name: "MTBF", unit: "h", better: "higher", target: 720 },
        { id: "mttr", name: "MTTR", unit: "h", better: "lower", target: 4 },
        { id: "pm_comp", name: "PM Compliance", unit: "%", better: "higher", target: 95 },
        { id: "backlog", name: "WO Backlog", unit: "weeks", better: "lower", target: 3 },
      ],
    },
    {
      id: "waste_esg",
      name: "Waste Management & ESG",
      short: "Waste / ESG",
      erp: "EHS / Environmental",
      icon: "♻",
      color: "#3d9b6e",
      description: "Tailings, effluent, emissions, water, circular recovery, permit compliance.",
      processTrack: "Identify → Assess → Control → Report",
      phases: [
        { id: "identify", label: "Stream Identified" },
        { id: "baseline", label: "Baseline Measure" },
        { id: "permit", label: "Permit / Legal" },
        { id: "design", label: "Control Design" },
        { id: "implement", label: "Implement" },
        { id: "monitor", label: "Monitor & Report" },
        { id: "audit", label: "Audit Ready" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "waste_t", name: "Waste to Landfill", unit: "t/mo", better: "lower", target: 200 },
        { id: "water", name: "Freshwater Intensity", unit: "m³/t", better: "lower", target: 2.5 },
        { id: "co2", name: "Scope 1+2 CO₂e", unit: "t/mo", better: "lower", target: 5000 },
        { id: "permit", name: "Permit Excursions", unit: "/yr", better: "lower", target: 0 },
      ],
    },
    {
      id: "safety",
      name: "Safety & Compliance",
      short: "Safety",
      erp: "EHS / Process Safety",
      icon: "⚠",
      color: "#d45a5a",
      description: "Process safety, permits, incidents, SIL, training compliance.",
      processTrack: "Report → Investigate → Correct → Verify",
      phases: [
        { id: "report", label: "Report / Near-Miss" },
        { id: "triage", label: "Triage Severity" },
        { id: "investigate", label: "Investigate" },
        { id: "actions", label: "Corrective Actions" },
        { id: "verify", label: "Verify Effectiveness" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "trir", name: "TRIR", unit: "rate", better: "lower", target: 0.5 },
        { id: "near_miss", name: "Near-Miss Reports", unit: "/mo", better: "higher", target: 20 },
        { id: "training", name: "Training Compliance", unit: "%", better: "higher", target: 100 },
        { id: "open_actions", name: "Open Safety Actions", unit: "count", better: "lower", target: 5 },
      ],
    },
    {
      id: "energy",
      name: "Energy & Utilities",
      short: "Energy",
      erp: "Utilities / Energy Mgmt",
      icon: "⚡",
      color: "#e0a040",
      description: "Power, heat, steam, water, compressed air for mineral processing.",
      processTrack: "Meter → Analyze → Optimize → Sustain",
      phases: [
        { id: "meter", label: "Meter & Baseline" },
        { id: "analyze", label: "Energy Analysis" },
        { id: "project", label: "Project Design" },
        { id: "implement", label: "Implement" },
        { id: "verify", label: "M&V Verify" },
        { id: "sustain", label: "Sustain" },
      ],
      kpis: [
        { id: "kwh_t", name: "kWh / tonne", unit: "kWh/t", better: "lower", target: 420 },
        { id: "peak_kw", name: "Peak Demand", unit: "MW", better: "lower", target: 45 },
        { id: "steam", name: "Steam Intensity", unit: "t steam/t", better: "lower", target: 0.8 },
        { id: "cost_energy", name: "Energy Cost / t", unit: "$/t", better: "lower", target: 35 },
      ],
    },
    {
      id: "mineral_recovery",
      name: "Mineral Recovery & Metallurgy",
      short: "Metallurgy",
      erp: "Metallurgical Accounting",
      icon: "◈",
      color: "#c4a35a",
      description: "Mass balance, by-product recovery, circuit configuration, lab-to-plant scale-up.",
      processTrack: "Lab → Pilot → Demo → Plant",
      phases: [
        { id: "lab", label: "Lab Testwork" },
        { id: "mass_bal", label: "Mass Balance" },
        { id: "pilot", label: "Pilot Plant" },
        { id: "demo", label: "Demo Scale" },
        { id: "eng", label: "Engineering" },
        { id: "commission", label: "Commission" },
        { id: "steady", label: "Steady State" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "recovery", name: "Overall Recovery", unit: "%", better: "higher", target: 90 },
        { id: "grade", name: "Product Grade", unit: "%", better: "higher", target: 99.5 },
        { id: "byproduct", name: "By-product Revenue", unit: "k$/mo", better: "higher", target: 200 },
        { id: "lockup", name: "Metal Lock-up (WIP)", unit: "t", better: "lower", target: 50 },
      ],
    },
    {
      id: "project_dev",
      name: "Project Development",
      short: "Projects",
      erp: "Project / CapEx",
      icon: "▦",
      color: "#6b8cae",
      description: "Greenfield/brownfield projects: FEL stages, capex, schedule, owner’s team.",
      processTrack: "FEL-1 → FEL-2 → FEL-3 → Execute → Handover",
      phases: [
        { id: "fel1", label: "FEL-1 Concept" },
        { id: "fel2", label: "FEL-2 Pre-Feasibility" },
        { id: "fel3", label: "FEL-3 Feasibility" },
        { id: "approve", label: "Board Approve" },
        { id: "execute", label: "Execute / Construct" },
        { id: "commission", label: "Commission" },
        { id: "handover", label: "Handover to Ops" },
        { id: "closed", label: "Close-Out" },
      ],
      kpis: [
        { id: "cpi", name: "Cost Performance (CPI)", unit: "ratio", better: "higher", target: 1.0 },
        { id: "spi", name: "Schedule Performance (SPI)", unit: "ratio", better: "higher", target: 1.0 },
        { id: "capex_var", name: "CapEx Variance", unit: "%", better: "lower", target: 5 },
        { id: "milestones", name: "Milestones On-Time", unit: "%", better: "higher", target: 90 },
      ],
    },
    {
      id: "finance",
      name: "Finance & Cost Control",
      short: "Finance",
      erp: "FI / CO / Product Costing",
      icon: "$",
      color: "#4a9b7a",
      description: "Product cost, variance, working capital, plant P&L, capex vs opex tracking.",
      processTrack: "Budget → Actual → Variance → Action",
      phases: [
        { id: "budget", label: "Budget Set" },
        { id: "forecast", label: "Forecast" },
        { id: "actual", label: "Actual Capture" },
        { id: "variance", label: "Variance Analysis" },
        { id: "action", label: "Corrective Action" },
        { id: "report", label: "Management Report" },
        { id: "closed", label: "Period Closed" },
      ],
      kpis: [
        { id: "unit_cost", name: "Cash Cost / t", unit: "$/t", better: "lower", target: 4200 },
        { id: "gross_margin", name: "Gross Margin", unit: "%", better: "higher", target: 28 },
        { id: "wc_days", name: "Working Capital Days", unit: "days", better: "lower", target: 45 },
        { id: "cost_var", name: "Cost Variance", unit: "%", better: "lower", target: 3 },
        { id: "ebitda", name: "Plant EBITDA", unit: "M$", better: "higher", target: 12 },
      ],
    },
    {
      id: "hedging",
      name: "Hedging & Commodity Risk",
      short: "Hedging",
      erp: "Treasury / Risk",
      icon: "⇄",
      color: "#9b6bb5",
      description: "Price risk on metals/FX: policy, hedge book, mark-to-market, settlement.",
      processTrack: "Policy → Position → Hedge → Settle → Report",
      phases: [
        { id: "policy", label: "Risk Policy" },
        { id: "exposure", label: "Exposure Mapping" },
        { id: "approve", label: "Hedge Approve" },
        { id: "execute", label: "Execute Hedge" },
        { id: "mtm", label: "Mark-to-Market" },
        { id: "settle", label: "Settle" },
        { id: "report", label: "Risk Report" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "hedge_ratio", name: "Hedge Ratio", unit: "%", better: "target", target: 60 },
        { id: "var", name: "VaR (1-day)", unit: "M$", better: "lower", target: 2.5 },
        { id: "mtm_pnl", name: "MtM P&L", unit: "M$", better: "higher", target: 0 },
        { id: "policy_breach", name: "Policy Breaches", unit: "/qtr", better: "lower", target: 0 },
      ],
    },
    {
      id: "marketing",
      name: "Marketing & Commercial",
      short: "Marketing",
      erp: "Commercial / Pricing",
      icon: "◎",
      color: "#3d8fb5",
      description: "Product positioning, offtake strategy, pricing, market intel for mineral products.",
      processTrack: "Insight → Offer → Negotiate → Contract → Review",
      phases: [
        { id: "insight", label: "Market Insight" },
        { id: "segment", label: "Segment / ICP" },
        { id: "offer", label: "Offer Design" },
        { id: "campaign", label: "Campaign / Outreach" },
        { id: "negotiate", label: "Negotiate" },
        { id: "contract", label: "Contract Signed" },
        { id: "review", label: "Performance Review" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "realized_price", name: "Realized Price vs Index", unit: "%", better: "higher", target: 100 },
        { id: "pipeline_value", name: "Commercial Pipeline", unit: "M$", better: "higher", target: 50 },
        { id: "win_rate", name: "Bid Win Rate", unit: "%", better: "higher", target: 35 },
        { id: "contract_cover", name: "Contracted Volume Cover", unit: "%", better: "higher", target: 70 },
      ],
    },
    {
      id: "crm",
      name: "CRM & Customer Ops",
      short: "CRM",
      erp: "CRM / Order-to-Cash",
      icon: "◉",
      color: "#5a7ec4",
      description: "Accounts, opportunities, complaints, SLAs, offtake relationship management.",
      processTrack: "Lead → Opportunity → Order → Fulfill → Support",
      phases: [
        { id: "lead", label: "Lead" },
        { id: "qualify", label: "Qualify" },
        { id: "opportunity", label: "Opportunity" },
        { id: "quote", label: "Quote / Term Sheet" },
        { id: "order", label: "Sales Order" },
        { id: "fulfill", label: "Fulfill / Ship" },
        { id: "invoice", label: "Invoice / Collect" },
        { id: "support", label: "After-Sales / NCR" },
        { id: "closed", label: "Closed-Won / Lost" },
      ],
      kpis: [
        { id: "nps", name: "Customer NPS", unit: "score", better: "higher", target: 40 },
        { id: "otif_cust", name: "Customer OTIF", unit: "%", better: "higher", target: 96 },
        { id: "dso", name: "DSO", unit: "days", better: "lower", target: 35 },
        { id: "complaint", name: "Open Complaints", unit: "count", better: "lower", target: 3 },
        { id: "renewal", name: "Contract Renewal Rate", unit: "%", better: "higher", target: 85 },
      ],
    },
    {
      id: "digital",
      name: "Digital, MES & Analytics",
      short: "Digital",
      erp: "MES / Historian / BI",
      icon: "▣",
      color: "#6a9bc4",
      description: "Sensors, historians, models, dashboards, digital twins for plant decisions.",
      processTrack: "Data → Model → Deploy → Adopt → Value",
      phases: [
        { id: "use_case", label: "Use Case" },
        { id: "data", label: "Data Ready" },
        { id: "model", label: "Model / Build" },
        { id: "pilot_ui", label: "Pilot UI" },
        { id: "integrate", label: "Integrate MES" },
        { id: "adopt", label: "Operator Adopt" },
        { id: "value", label: "Value Proven" },
        { id: "closed", label: "Closed" },
      ],
      kpis: [
        { id: "data_uptime", name: "Tag Data Uptime", unit: "%", better: "higher", target: 99 },
        { id: "model_acc", name: "Model Accuracy", unit: "%", better: "higher", target: 90 },
        { id: "adoption", name: "Operator Adoption", unit: "%", better: "higher", target: 80 },
        { id: "value_usd", name: "Verified Value", unit: "k$/yr", better: "higher", target: 500 },
      ],
    },
    {
      id: "planning",
      name: "Production Planning & S&OP",
      short: "S&OP",
      erp: "PP / APO / S&OP",
      icon: "☰",
      color: "#8a7a9a",
      description: "Monthly S&OP, campaign planning, constraint-based scheduling across sites.",
      processTrack: "Demand → Supply → Balance → Commit → Execute",
      phases: [
        { id: "demand", label: "Demand Review" },
        { id: "supply", label: "Supply Review" },
        { id: "pre_sop", label: "Pre-S&OP" },
        { id: "exec_sop", label: "Executive S&OP" },
        { id: "commit", label: "Plan Commit" },
        { id: "dispatch", label: "Weekly Dispatch" },
        { id: "closed", label: "Cycle Closed" },
      ],
      kpis: [
        { id: "plan_acc", name: "Plan Accuracy", unit: "%", better: "higher", target: 90 },
        { id: "atp", name: "ATP / Promise Keep", unit: "%", better: "higher", target: 95 },
        { id: "changeovers", name: "Unplanned Changeovers", unit: "/mo", better: "lower", target: 4 },
        { id: "capacity_util", name: "Capacity Utilization", unit: "%", better: "target", target: 88 },
      ],
    },
  ];

  const LOCATIONS = [
    "Concentration Plant — Site A",
    "Hydromet / Leach — Site B",
    "Smelter & Refinery — Site C",
    "Downstream Processing — Site D",
    "Central Lab / Pilot Plant",
    "Project Development / Multi-site",
    "Commercial / HQ",
    "Treasury / Finance HQ",
  ];

  const TEAMS = [
    "Project Development",
    "Process Engineering",
    "Operations",
    "Supply Chain",
    "Procurement",
    "Quality / Lab",
    "Maintenance",
    "EHS / Waste",
    "Finance / Controlling",
    "Treasury / Risk",
    "Marketing / Commercial",
    "Customer Success / CRM",
    "Data & Analytics",
    "Continuous Improvement",
    "R&D / Metallurgy",
    "Production Planning",
  ];

  const PRIORITIES = ["Low", "Medium", "High", "Critical"];

  const RECORD_TYPES = [
    { id: "idea", label: "Improvement Idea" },
    { id: "process", label: "Process / Work Order Track" },
    { id: "project", label: "CapEx / Project" },
    { id: "commercial", label: "Commercial / CRM Deal" },
    { id: "finance", label: "Finance / Hedge Action" },
  ];

  function moduleById(id) {
    return MODULES.find((m) => m.id === id) || MODULES[0];
  }

  function phaseLabel(moduleId, phaseId) {
    const m = moduleById(moduleId);
    const p = (m.phases || []).find((x) => x.id === phaseId);
    return p ? p.label : phaseId;
  }

  function uid() {
    return "id_" + Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
  }

  /** Build default KPI snapshot from module targets with slight variance */
  function kpiSnapshot(moduleId, overrides) {
    const m = moduleById(moduleId);
    const snap = {};
    (m.kpis || []).forEach((k) => {
      const base = k.target;
      const jitter = typeof base === "number" ? base * (0.92 + Math.random() * 0.12) : base;
      snap[k.id] = {
        actual: overrides && overrides[k.id] != null ? overrides[k.id] : Math.round(jitter * 100) / 100,
        target: k.target,
        unit: k.unit,
        name: k.name,
        better: k.better,
      };
    });
    return snap;
  }

  function seedRecords() {
    const now = Date.now();
    const d = 86400000;
    const mk = (partial) => {
      const mod = partial.module;
      return {
        id: uid(),
        votes: 0,
        voted: false,
        submitter: "",
        impact: "",
        recordType: "idea",
        createdAt: new Date(now - 10 * d).toISOString(),
        updatedAt: new Date(now - 2 * d).toISOString(),
        kpis: kpiSnapshot(mod),
        ...partial,
      };
    };

    return [
      mk({
        title: "Campaign #47 flotation — raise recovery to plan",
        problem: "Circuit recovery 1.8pp below plan; operator dosing varies by shift.",
        solution: "Lock golden recipe + SPC on pH/reagent; shift huddle KPI board.",
        impact: "Restore plan recovery; cut reagent variance",
        module: "production",
        phase: "execute",
        recordType: "process",
        priority: "High",
        location: "Concentration Plant — Site A",
        team: "Operations",
        lead: "Maya Chen",
        submitter: "Shift lead A",
        votes: 12,
        kpis: kpiSnapshot("production", { recovery: 90.2, oee: 81, downtime: 11 }),
      }),
      mk({
        title: "Leach temperature profile SOP standardization",
        problem: "±3% recovery swing week-to-week from ramp differences.",
        solution: "Staged temp profile, sensors, train all crews.",
        impact: "+1.5pp recovery",
        module: "process_efficiency",
        phase: "pilot",
        priority: "High",
        location: "Hydromet / Leach — Site B",
        team: "Process Engineering",
        lead: "J. Ortiz",
        votes: 18,
        kpis: kpiSnapshot("process_efficiency", { recovery_delta: 0.9, reagent_use: 13.2 }),
      }),
      mk({
        title: "Dual-source concentrate — reduce single-mine risk",
        problem: "80% volume one mine; grade swings idle thermal plant.",
        solution: "Qualify second source + blend windows + safety stock.",
        impact: "OTIF up; downtime down",
        module: "supply_chain",
        phase: "contract",
        priority: "Critical",
        location: "Concentration Plant — Site A",
        team: "Supply Chain",
        lead: "Priya Nair",
        votes: 24,
        kpis: kpiSnapshot("supply_chain", { otif: 88, stockout: 2, inventory_days: 34 }),
      }),
      mk({
        title: "Annual reagent frame agreement — P2P savings",
        problem: "Spot buys and maverick MRO spend inflate unit cost.",
        solution: "Frame contracts + catalog + 3-way match enforcement.",
        impact: "5% purchase savings",
        module: "procurement",
        phase: "rfq",
        recordType: "process",
        priority: "Medium",
        location: "Project Development / Multi-site",
        team: "Procurement",
        lead: "Sam Okonkwo",
        votes: 9,
        kpis: kpiSnapshot("procurement", { savings: 2.1, maverick: 7, cycle_po: 9 }),
      }),
      mk({
        title: "WIP lot traceability — warehouse barcode rollout",
        problem: "Manual WIP tickets; inventory accuracy 94%.",
        solution: "Barcode putaway/pick for WIP cages; daily cycle count.",
        impact: "Accuracy → 99%",
        module: "inventory",
        phase: "putaway",
        priority: "High",
        location: "Smelter & Refinery — Site C",
        team: "Operations",
        lead: "R. Diaz",
        votes: 11,
        kpis: kpiSnapshot("inventory", { accuracy: 94.2, wip_days: 7.5 }),
      }),
      mk({
        title: "Customer CoA SLA — cut assay turnaround",
        problem: "CoA late 12% of shipments; customer complaints rising.",
        solution: "LIMS priority queue + auto CoA PDF to CRM.",
        impact: "CoA on-time 99%",
        module: "quality",
        phase: "assay",
        priority: "High",
        location: "Central Lab / Pilot Plant",
        team: "Quality / Lab",
        lead: "Rachel Cho",
        votes: 15,
        kpis: kpiSnapshot("quality", { coa_ontime: 88, fpy: 95.5 }),
      }),
      mk({
        title: "Mill gearbox PM compliance recovery",
        problem: "PM compliance 78%; rising vibration on Ball Mill #2.",
        solution: "Criticality-based PM, spare kit, condition monitoring.",
        impact: "MTBF↑ MTTR↓",
        module: "maintenance",
        phase: "plan",
        recordType: "process",
        priority: "Critical",
        location: "Concentration Plant — Site A",
        team: "Maintenance",
        lead: "Derek Walsh",
        votes: 14,
        kpis: kpiSnapshot("maintenance", { pm_comp: 78, mttr: 6.5, backlog: 5.2 }),
      }),
      mk({
        title: "Process sludge metal recovery vs landfill",
        problem: "Recoverable metal landfilled; disposal cost rising.",
        solution: "Selective leach pilot + permit path.",
        impact: "Waste↓ by-product revenue↑",
        module: "waste_esg",
        phase: "design",
        priority: "High",
        location: "Smelter & Refinery — Site C",
        team: "EHS / Waste",
        lead: "Andre Brooks",
        votes: 20,
        kpis: kpiSnapshot("waste_esg", { waste_t: 280, water: 2.9 }),
      }),
      mk({
        title: "Autoclave feed interlock SIL upgrade",
        problem: "Near-miss on partial vent; interlock gaps.",
        solution: "SIL review, dual transmitters, hard trip.",
        impact: "Process safety risk↓",
        module: "safety",
        phase: "actions",
        priority: "Critical",
        location: "Hydromet / Leach — Site B",
        team: "EHS / Waste",
        lead: "Safety committee",
        votes: 17,
        kpis: kpiSnapshot("safety", { open_actions: 12, training: 94 }),
      }),
      mk({
        title: "Peak shaving — mill start sequencing",
        problem: "Peak MW charges inflate energy $/t.",
        solution: "Staggered mill starts + demand response SOP.",
        impact: "Peak MW and $/t down",
        module: "energy",
        phase: "project",
        priority: "Medium",
        location: "Concentration Plant — Site A",
        team: "Continuous Improvement",
        lead: "Tom Hale",
        votes: 8,
        kpis: kpiSnapshot("energy", { peak_kw: 49, kwh_t: 455, cost_energy: 38 }),
      }),
      mk({
        title: "By-product recovery circuit — FEL-2",
        problem: "Secondary stream not recovered; revenue left on table.",
        solution: "Lab → pilot mass balance; FEL-2 package.",
        impact: "By-product k$/mo",
        module: "mineral_recovery",
        phase: "pilot",
        recordType: "project",
        priority: "High",
        location: "Central Lab / Pilot Plant",
        team: "R&D / Metallurgy",
        lead: "Elena Volkov",
        votes: 13,
        kpis: kpiSnapshot("mineral_recovery", { recovery: 86, byproduct: 40 }),
      }),
      mk({
        title: "Site D expansion — FEL-3 feasibility",
        problem: "Capacity constraint; market demand exceeds ATP.",
        solution: "FEL-3 package, capex estimate ±15%, schedule.",
        impact: "Board decision package",
        module: "project_dev",
        phase: "fel3",
        recordType: "project",
        priority: "Critical",
        location: "Downstream Processing — Site D",
        team: "Project Development",
        lead: "Sofia Reyes",
        votes: 16,
        kpis: kpiSnapshot("project_dev", { cpi: 0.97, spi: 0.94, capex_var: 8 }),
      }),
      mk({
        title: "Q3 cash cost reduction program — Site B",
        problem: "Cash cost $4,650/t vs target $4,200; margin pressure.",
        solution: "Variance deep-dive: reagents, energy, recovery loss; action pack.",
        impact: "Unit cost toward target",
        module: "finance",
        phase: "action",
        recordType: "finance",
        priority: "Critical",
        location: "Hydromet / Leach — Site B",
        team: "Finance / Controlling",
        lead: "A. Mehta",
        votes: 19,
        kpis: kpiSnapshot("finance", { unit_cost: 4650, gross_margin: 22, cost_var: 7.2 }),
      }),
      mk({
        title: "H2 metal price hedge book — 60% policy band",
        problem: "Unhedged exposure; VaR above board limit on price spike.",
        solution: "Layer forwards to 55–65% hedge ratio; weekly MtM.",
        impact: "VaR within policy",
        module: "hedging",
        phase: "execute",
        recordType: "finance",
        priority: "High",
        location: "Treasury / Finance HQ",
        team: "Treasury / Risk",
        lead: "L. Berg",
        votes: 10,
        kpis: kpiSnapshot("hedging", { hedge_ratio: 48, var: 3.1, policy_breach: 1 }),
      }),
      mk({
        title: "Battery-grade product positioning — offtake campaign",
        problem: "Commodity pricing only; miss premium segments.",
        solution: "ICP for battery OEMs; premium spec pack; outreach Q3.",
        impact: "Realized price vs index ↑",
        module: "marketing",
        phase: "campaign",
        recordType: "commercial",
        priority: "High",
        location: "Commercial / HQ",
        team: "Marketing / Commercial",
        lead: "N. Park",
        votes: 14,
        kpis: kpiSnapshot("marketing", { realized_price: 97, pipeline_value: 32, win_rate: 28 }),
      }),
      mk({
        title: "Offtake renewal — Account: NorthVolt Materials",
        problem: "Contract expires in 5 months; competitor RFQ open.",
        solution: "Executive QBR, flexible volume band, CoA SLA upgrade.",
        impact: "Renewal + DSO stable",
        module: "crm",
        phase: "opportunity",
        recordType: "commercial",
        priority: "Critical",
        location: "Commercial / HQ",
        team: "Customer Success / CRM",
        lead: "C. Laurent",
        votes: 21,
        kpis: kpiSnapshot("crm", { nps: 32, dso: 42, renewal: 0, otif_cust: 94 }),
      }),
      mk({
        title: "Predictive flotation dose model → control room",
        problem: "Manual dose; cost and recovery variance.",
        solution: "Historian features + model + MES advisory mode.",
        impact: "Reagent −10%, recovery +0.7pp",
        module: "digital",
        phase: "pilot_ui",
        priority: "Medium",
        location: "Concentration Plant — Site A",
        team: "Data & Analytics",
        lead: "Elena Volkov",
        votes: 12,
        kpis: kpiSnapshot("digital", { model_acc: 86, adoption: 35, data_uptime: 97.5 }),
      }),
      mk({
        title: "Monthly S&OP — align offtake with Site C outage",
        problem: "Planned furnace outage not reflected in ATP promises.",
        solution: "Integrated supply review + commercial freeze window.",
        impact: "Promise keep ↑; changeovers ↓",
        module: "planning",
        phase: "pre_sop",
        recordType: "process",
        priority: "High",
        location: "Project Development / Multi-site",
        team: "Production Planning",
        lead: "K. Singh",
        votes: 11,
        kpis: kpiSnapshot("planning", { plan_acc: 84, atp: 89, capacity_util: 91 }),
      }),
    ];
  }

  return {
    MODULES,
    LOCATIONS,
    TEAMS,
    PRIORITIES,
    RECORD_TYPES,
    moduleById,
    phaseLabel,
    kpiSnapshot,
    seedRecords,
    uid,
  };
})();
